CREATE TABLE lancamento (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	descricao VARCHAR(80) NOT NULL,
	valor DECIMAL(10,2) NOT NULL,
	data DATE NOT NULL,
	tipo VARCHAR(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;